In [2]:
import numpy as np

In [7]:
A = np.array([[1,0,1,1,0,1,1,0,0],[1,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,1,0],[1,0,0,0,0,10,0,1,1]])
print('DTM의 크기(shape) :', np.shape(A))
print(A)

DTM의 크기(shape) : (4, 9)
[[ 1  0  1  1  0  1  1  0  0]
 [ 1  0  0  1  1  0  1  0  0]
 [ 0  1  1  0  2  0  0  1  0]
 [ 1  0  0  0  0 10  0  1  1]]


In [8]:
U, s, VT = np.linalg.svd(A, full_matrices = True)
print("="*50)
print('행렬 U :')
print(U.round(2))
print('행렬 U의 크기(shape) :',np.shape(U))
print("="*50)
print('행렬 sigma :')
print(s.round(2))
print('행렬 sigma의 크기(shape) :',np.shape(s))
print("="*50)
print('행렬 V^t :')
print(VT.round(2))
print('행렬 V^t의 크기(shape) :',np.shape(VT))


행렬 U :
[[-0.11 -0.42  0.6  -0.68]
 [-0.01 -0.54  0.44  0.72]
 [-0.01 -0.73 -0.67 -0.14]
 [-0.99  0.06 -0.06  0.07]]
행렬 U의 크기(shape) : (4, 4)
행렬 sigma :
[10.21  2.99  2.21  0.95]
행렬 sigma의 크기(shape) : (4,)
행렬 V^t :
[[-0.11 -0.   -0.01 -0.01 -0.   -0.98 -0.01 -0.1  -0.1 ]
 [-0.3  -0.24 -0.38 -0.32 -0.67  0.07 -0.32 -0.22  0.02]
 [ 0.44 -0.3  -0.03  0.47 -0.41 -0.02  0.47 -0.33 -0.03]
 [ 0.12 -0.14 -0.85  0.05  0.47 -0.01  0.05 -0.07  0.07]
 [-0.28 -0.83  0.28  0.14  0.31  0.04 -0.18 -0.08 -0.04]
 [-0.62  0.29 -0.12  0.69 -0.04  0.08 -0.03 -0.1  -0.09]
 [-0.47 -0.08 -0.02 -0.35  0.02  0.04  0.8   0.05  0.02]
 [ 0.02 -0.22 -0.17  0.2  -0.26 -0.09  0.03  0.9  -0.02]
 [-0.06 -0.    0.06  0.1  -0.03 -0.09 -0.01 -0.    0.99]]
행렬 V^t의 크기(shape) : (9, 9)
